all:
  vars:
    control_plane_endpoint: 192.168.2.200
    load_balancer_ip_pool:
      - 192.168.2.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.2.110, mac: '24:4b:fe:c8:24:37', disk: nvme0n1, network_interface: enp2s0f0}
#    workers:
#      hosts:
#        metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f4:d6', disk: sda, network_interface: eno1}
#
